### ISSUE TITLE
CI/CD Pipeline

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#1]
- run ci tests on pr and merges
- automatic builds and releases of `liked` and docker image on master and version tags
- cross-platform building e.g. arm64 (nice-to-have, skip if time consuming?)
- ~~(use github runner since we expect this to be reused by likecoin org?)~~ use circle ci

- [x] Setup CircleCI for PR and merged commits
- [x] Build binary for multiple architectures
- [ ] Build docker images for multiple architectures
- [ ] Handle docker image deployment
- [ ] Create script to handle binary releases on GitHub

**Comment by rickmak** [comment]
Let's use platform like circleci for opensource project. I expect the ci script only calling makefile. All logic and switch at Makefile.

For binary build, we can use github release or pin the file at ipfs?

**Comment by rickmak** [comment]
I think all are done?

The docker-image will be manually release.
The github binary release already working at github action.
