### ISSUE TITLE
Update relayer setup guide

### ISSUE THREAD

**Issue by hochiw** [oursky/likecoin-chain#100]
https://www.notion.so/oursky/LIKE-OSMO-Relayer-Setup-43f75776cc094b38a880fe1cb68cc966

based on how likecoin team is handling the packet relaying we presume the listening relayer is not working at the moment. 

- [x] Upgrade guide to v1.0.0 based
- [x] Add shell script to run manual packet relaying automatically
- [x] Revamp systemctl service
- [x] Add heads-up for listening relayer being unusable

**Comment by chihimng** [comment]
do we need to submit this to upstream?

@hochiw @rickmak

**Comment by rickmak** [comment]
I think the objective is to operate a relayer ourself and make the information publicly available. It is important for our dev to gain some experience on the relayer and see what will happen in the actual production environment.

So your answer is not submit to upstream, but create a separate site for such resource.

**Comment by mitchellchou** [comment]
The guide need public (waiting for relayer setup)

**Comment by mitchellchou** [comment]
close and wait for: https://github.com/oursky/likecoin-chain/issues/142
