### ISSUE TITLE
Deploy faucet to testnet

### ISSUE THREAD

**Issue by thomas-tai-oursky** [oursky/likecoin-chain#102]

**Comment by hochiw** [comment]
@thomas-tai-oursky @mitchellchou 
Here are some steps you may follow to test this out.
1. Ensure you have Keplr installed on Chrome
2. Prepare a wallet
3. Head to https://ipfs.io/ipfs/Qmb5bQNS6cVfro8dGZcRTdznVuiH4Wwv3RAmqZ9ecJo8Ti
4. Click `Click to add to Keplr`
5. You should see a Keplr prompt, Click accept
6. You should now see the 'LikeCoin public test chain' option in the chain list
7. Select 'LikeCoin public test chain'
8. Click your wallet address to copy it
9. Go to LikeCoin discord server https://discord.com/invite/likecoin
10. Head to the #faucet-testnet channel
11. Type `/faucet <your_address>`
12. Send the message
13. If the transaction succeeds, you should see it being reflected by the bot
14. Open Keplr
15. You should now see 1000EKIL in your account (if you don't try to switch to another network and back)
