### ISSUE TITLE
[Chain Upgrade] Test upgrade with production state

### ISSUE THREAD

**Issue by hochiw** [oursky/likecoin-chain#103]

**Comment by hochiw** [comment]
@chihimng talked to @rickmak about this test, since the production data needs its corresponding genesis I suppose we will not be able to test the upgrade via proposal. we think the following shall be tested.

1. Migration (not sure how we can do this without upgrade handlers)
2. Query and mutate data with new binary 

See if you have any idea on the migration part or if there's anything else that we should test :adore2x:

**Comment by chihimng** [comment]
@hochiw just a quick idea, not sure if works:

0. obtain snapshot of mainnet
1. make a script so we can hard fork the appState: inject a new account with tons of tokens, and if possible all existing validators
(ref old migration method: https://github.com/cosmos/cosmos-sdk/tree/v0.42.11/x/genutil/legacy)
2. (with fotan binary) setup validator with the injected account, make proposal for upgrade to laichikok

cc @rickmak

**Comment by hochiw** [comment]
@chihimng cc @rickmak just tried this locally, can't query balances from the injected account, it seems like the migration only modifies the genesis file in which I think the node doesn't read it anymore when there is data :sadFrog: (tested this by restarting the node after letting it generate a few blocks and deleting the genesis.json)

**Comment by chihimng** [comment]
@hochiw did you call `unsafe-reset-all`? also ref this doc: https://docs.cosmos.network/v0.42/migrations/chain-upgrade-guide-040.html

**Comment by hochiw** [comment]
Tested with Nov snapshot, seems to consume 12gb (according to htop) - 20gb (according to azure metrics) ram, so I think 32gb would be safe.

**Comment by hochiw** [comment]
@chihimng https://ourskylikecoin.blob.core.windows.net/mainnet-snapshot/genesis-03-31-snapshot.tar.gz?sp=r&st=2022-04-04T07:06:34Z&se=2023-01-01T15:06:34Z&spr=https&sv=2020-08-04&sr=b&sig=H0zS4REUUbabumxbEwhFpUKkO1gRyNtswWIp2k966aE%3D

**Comment by chihimng** [comment]
this was not done, only exported latest state successfully

next step is to follow https://www.notion.so/oursky/LikeCoin-Mainnet-Migration-Test-3445bad868fe41829f9ececf81fa7952 to test the whole migration flow

**Comment by mitchellchou** [comment]
need around 8 points
