### ISSUE TITLE
Code changes for sdk upgrade to 0.44+prefix

### ISSUE THREAD

**Issue by thomas-tai-oursky** [oursky/likecoin-chain#104]
- Rebase feat/sdk-0.44 onto upstream master
- Review and cherrypick changes on upstream chain code changes for prefix
- Fix issue found on ibc-go v2 migration

**Comment by chihimng** [comment]
please recheck all migration code required from all migration docs (sdk v0.44, ibc sdk->1, ibc 1->2, module migration - see if iscn requires any change)
