### ISSUE TITLE
Test sdk upgrade to 0.44+prefix

### ISSUE THREAD

**Issue by thomas-tai-oursky** [oursky/likecoin-chain#105]
- Review test cases for prefix changes, add if not enough
- Run consensus snapshot weekly, document test flow

**Comment by chihimng** [comment]
test ibc via https://github.com/cosmos/ibc-go/tree/v2.0.3/testing

**Comment by chihimng** [comment]
also recheck all migration code required from all migration docs (sdk v0.44, ibc sdk->1, ibc 1->2, module migration - see if iscn requires any change)
