### ISSUE TITLE
Upgrade skynet to v2.0.0

### ISSUE THREAD

**Issue by hochiw** [oursky/likecoin-chain#128]
Follow https://github.com/oursky/likecoin-docs/blob/46a3fb5e3856eb123edddf95272e08fa0d886e3b/validator/laichikok-upgrade/README.md
and upgrade skynet to v2.0.0

**Comment by chihimng** [comment]
also ref this doc: https://github.com/oursky/likecoin-docs/pull/2

**Comment by chihimng** [comment]
done
