### ISSUE TITLE
Handle testnet DNS alias resolve

### ISSUE THREAD

**Issue by hochiw** [oursky/likecoin-chain#130]
- Should follow likecoin structure
- LCD -> localhost:1317
- RPC -> localhost:26657

**Comment by rickmak** [comment]
Don't understand....

**Comment by hochiw** [comment]
oh already done, just forgot to setup nginx before

**Comment by rickmak** [comment]
Do you have setup notes for the node?

**Comment by rickmak** [comment]
@hochiw Please also setup the CORS to *

**Comment by hochiw** [comment]
> Do you have setup notes for the node?

on the node itself or nginx?

> @hochiw Please also setup the CORS to *

okay
