### ISSUE TITLE
Handle skynet auto binary swap

### ISSUE THREAD

**Issue by hochiw** [oursky/likecoin-chain#134]
- Create script to fetch the latest minor version of the binary
- If no new version, exit
- else 
    - Backup state
    - Stop chain, swap binary and restart 
    - Create cronjob to run this script

**Comment by chihimng** [comment]
check for newer pre-release instead? say 2.0.0-alpha1 to 2.0.0-alpha2

**Comment by hochiw** [comment]
https://github.com/oursky/likecoin-skynet/commit/ce180f449f3fd966727aa8aebafc32514a73df41
