### ISSUE TITLE
[v2.0 Rollout] Emergency response plan

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#137]
Plan for the worst, draft rollback / hotfix plans and policy

- update chain upgrade docs to add rollback steps, and add more info on the upgrade (e.g. chain-id same, upgrade duration, etc.)
- test rollback command

**Comment by chihimng** [comment]
ref https://github.com/cosmos/gaia/blob/main/docs/migration/cosmoshub-4-delta-upgrade.md

**Comment by chihimng** [comment]
flag should be `--unsafe-skip-upgrades` (with s)

**Comment by chihimng** [comment]
wip at https://github.com/oursky/likecoin-docs/pull/2

**Comment by mitchellchou** [comment]
Ask LikeCoin for should using --x-crisis-skip-assert-invariants as recommended in gaia's upgrade guide (If they have ever used

**Comment by chihimng** [comment]
for `--x-crisis-skip-assert-invariants`, depends on liker land's opinion, and our performance testing in #141; let's not track here

**Comment by chihimng** [comment]
added rollback instructions to https://github.com/oursky/likecoin-docs/pull/2
and tested to rollback
