### ISSUE TITLE
[NFT] Add versioning to protobuf schemas

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#139]
use v1beta1 or v1

**Comment by mitchellchou** [comment]
need to do once before testnet, will affect other nft developer

**Comment by chihimng** [comment]
Some issue with proceeding:

The best practice is to name the package `likechain.likenft.v1` & put the proto files in `/proto/likechain/likenft/v1/xxx.proto`, & rest api path `/likechain/likenft/v1/xxx`
(from observation big chains like osmosis / evmos / cro follows this)

But this would not work with ignite cli (starport): it expects proto files to be placed in `/proto/likenft`, and package name `likecoin.likechain.likenft`...

There seems to be no option for custom proto path or module name; dev will need workaround by adding a temporary simlink from the expected path to the actual proto path when scaffolding + rename the generated package name / rest api path

(Dev will have to rename the package line anyways, in order to align with iscn's `likechain.iscn` format; the biggest pain point is to add simlink everytime scaffold command is used)

@Rico-Wong @rickmak any opinion on this?

**Comment by mitchellchou** [comment]
add instruction in readme
