### ISSUE TITLE
[NFT Marketplace] Review spec to support membership / subscription apps

### ISSUE THREAD

**Issue by thomas-tai-oursky** [oursky/likecoin-chain#140]
## Reference
- Clinet thread: [NFT requirements unique to LikeCoin](https://3.basecamp.com/3096882/buckets/25656427/messages/4719661777)

**Comment by thomas-tai-oursky** [comment]
Can start after roll out of v2.0.0 testnet

**Comment by chihimng** [comment]
- allow relating account to nft class (in addition to iscn to nft class)
- for marketplace, add pay to mint with min price & max supply (in addition to buyer / seller offer)
- for seller offer, will not handle invalidating offers for transferred out tokens, it should error on execute offer, and dapp ui / query should check for validity beforehand. (& maybe add a cleanup function somewhere?)

**Comment by mitchellchou** [comment]
1. Will release a marketplace draft in the mid April
2. Can start with some confirmed the spec 

- [ ] @chihimng please provide the list with confirmed and TBC items

**Comment by chihimng** [comment]
@mitchellchou let's continue this at #8 story
