### ISSUE TITLE
Mainnet upgrade resource planning

### ISSUE THREAD

**Issue by thomas-tai-oursky** [oursky/likecoin-chain#141]
Check if 16gig ram is enough. If yes, update migration doc.

**Comment by chihimng** [comment]
also for hdd, since cosmovisor will copy data folder for backup, need 2x the min storage

**Comment by hochiw** [comment]
will be testing oursky/likecoin-chain#103 again and see whether we should go for 16gb or 32gb.

**Comment by chihimng** [comment]
if resources requirement is huge, try `--x-crisis-skip-assert-invariants`

**Comment by hochiw** [comment]
Changed to 32GB according to the result from oursky/likecoin-chain#103, drafted a tiny system requirement section and sent to @chihimng to update his pr

**Comment by hochiw** [comment]
https://github.com/oursky/likecoin-docs/pull/2
