### ISSUE TITLE
Test proposal upgrade from v1.2.0 to same version

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likecoin-chain#145]
Filled by Mitchell please correct if I'm wrong

## Background
We have already tested v1.2.0 to v2.0.0, but for the cosmovisor upgrade exercise on testnet (for existing validators), we will not upgrade to the next release yet, so need to see if we can swap to the same binary, or if we need to make a customized build for the exercise

## Todo
- [ ] Test proposal upgrade from v1.2.0 to v1.2.0, without new upgrade handler

**Comment by chihimng** [comment]
@mitchellchou i've updated the content a bit 🙏

**Comment by chihimng** [comment]
tested that it doesn't work without an upgrade handler, so will make a demo build for this

**Comment by chihimng** [comment]
made a new build for upgrade demo based on v1.2, tested working: https://github.com/oursky/likecoin-chain/releases/tag/v1.2.0-upgrade-demo

and drafting a exercise guide based on the current upgrade info docs: https://hackmd.io/@chihimng/B18kHIuf9

**Comment by mitchellchou** [comment]
Please update the document icluding

**Comment by mitchellchou** [comment]
@rickmak will discuss with William the next steps

**Comment by chihimng** [comment]
followup is to test if newcomers can join testnet with v1.2.0-upgrade-demo and replay blocks after the exercise; if can't, advice newcomers to either state sync with latest version binary, or replay blocks with each old version binary as instructed by cosmovisor guide.

**Comment by chihimng** [comment]
> rickmak will discuss with William the next steps
this is for mainnet state sync issue, not really related to this
