### ISSUE TITLE
Handle testnet halted incident

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#154]
- Migrate node1 and node2 to act as seed mode node - not validator
- Add 2 new validators, with pex off + consistent connection to trusted peers

Ref https://docs.tendermint.com/master/spec/p2p/node.html
Ref https://docs.tendermint.com/master/nodes/validators.html

**Comment by hochiw** [comment]
https://github.com/oursky/likecoin.oursky.dev/tree/master/node-vm-testnet-faseng
