### ISSUE TITLE
[v2.0.0 Upgrade] ISCN

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likecoin-chain#158]
- [ ] Create an ISCN
```
./liked tx iscn create-iscn ./iscn.json --from account --chain-id test
```

- [ ] Perform chain upgrade

- [ ] Query ISCN
```
./liked q iscn record $ISCN_URL
```

- [ ] Update ISCN
```
./liked tx iscn update-iscn $ISCN_URL ./new_iscn.json --from account --chain-id test
```

- [ ] Change ISCN ownership
```
./liked tx iscn $ISCN_URL $NEW_ADDRESS --from account --chain-id test
```

- [ ] Query ISCN Again
```
./liked q iscn record $ISCN_URL
```

- [ ] Upgrade is successful if the queried data is expected after each transaction

## Reference
[#96 (oursky/likecoin-chain#95)](https://zube.io/oursky/likecoin-chain/c/96)

**Comment by chihimng** [comment]
this overlaps with #103, i think we can call it ok if we can query past know data after migrating from mainnet snapshot
