### ISSUE TITLE
[v2.0.0 Upgrade] IBC Transfer

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likecoin-chain#159]
- [ ] Setup OSMO chain and LIKE chain
https://www.notion.so/oursky/LikeCoin-Chain-Upgrade-Test-11cd6c3fc70c46d39dfb67d3af5663ad

- [ ] Setup relayer 
https://www.notion.so/oursky/LIKE-OSMO-Relayer-Setup-43f75776cc094b38a880fe1cb68cc966

- [ ] Perform IBC transaction
```
./liked tx ibc-transfer transfer transfer channel-0 $ACCOUNT2 100000nanolike --from $ACCOUNT1 --chain-id test --keyring-backend test -y

./osmosisd tx ibc-transfer transfer transfer channel-0 $ACCOUNT1 100000uosmo --from $ACCOUNT2 --chain-id test --keyring-backend test -y
```

- [ ] Check balances for each account 
```
./liked q balances $ACCOUNT1
./osmosisd q balances $ACCOUNT2
```

- [ ] Perform chain upgrade

- [ ] Perform IBC transaction again
```
./liked tx ibc-transfer transfer transfer channel-0 $ACCOUNT2 100000nanolike --from $ACCOUNT1 --chain-id test --keyring-backend test -y

./osmosisd tx ibc-transfer transfer transfer channel-0 $ACCOUNT1 100000uosmo --from $ACCOUNT2 --chain-id test --keyring-backend test -y
```

- [ ] Check balances for each account again
```
./liked q balances $ACCOUNT1
./osmosisd q balances $ACCOUNT2
```

## Reference
oursky/likecoin-chain#96

**Comment by hochiw** [comment]
Tested with local gaiad v7.0.0 node and liked v1.2.0 node with ibc relayer v1.0.0.

100000stake and 100000nanolike were sent via ibc channels to testing accounts from both chains pre-upgrade.

Inquiring balances and ibc transactions yields no unexpected result after upgrading liked node to custom v2.0.0 build from https://github.com/oursky/likecoin-chain/pull/186
