### ISSUE TITLE
[NFT] Mechanism for class owner to preset metadata for pay-to-mint nfts

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#177]
Ref oursky/likecoin-chain#8 
Design a mechanism for this. Follow up oursky/likecoin-chain#150

**Comment by chihimng** [comment]
for random, derive from last block hash?

**Comment by mitchellchou** [comment]
@chihimng Could ask May for some reference

**Comment by mitchellchou** [comment]
Confirming if SDK can support query old Hash
WIP doc: https://www.notion.so/oursky/NFT-Drop-Ideas-f97a822418f24b4088bf4cb98dfdc01e

**Comment by chihimng** [comment]
Done, Updated planning in oursky/likecoin-chain#192
