### ISSUE TITLE
Run assert invariants on upgraded mainnet fork

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#184]
--inv-checks-period=1

**Comment by hochiw** [comment]
testing on mainnet migration machine.

**Comment by hochiw** [comment]
Test with mainnet data failed at crisis invariant check.

[fail.log](https://github.com/oursky/likecoin-chain/files/8451337/fail.log)

**Comment by mitchellchou** [comment]
goal: 
1. test without prefix change 
2. test prefix migration

Todo:
1. test with testnet-3 snapshot
2. test with mainnet snapshot

**Comment by hochiw** [comment]
- [x] Testing testnet modified genesis import with `--inv-check-period=1`
- [ ]  Testing testnet upgrade to custom binary with only sdk upgrade
- [ ] Testing testnet upgrade with prefix
