### ISSUE TITLE
Update usages of unsafe-reset-all

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#195]
cmd relocated after sdk upgrade

**Comment by chihimng** [comment]
Ref #194

**Comment by nnkken** [comment]
Just found that the `test-chains/prefix-test/completion.sh` script is actually something I generated locally for testing...🙇‍♂️
So seems no script in the repo is using `unsafe-reset-all`.

**Comment by rickmak** [comment]
No `unsafe-reset-all` found in repo.
