### ISSUE TITLE
Devnet Setup

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#2]
- Host a devnet with multiple machines for testing dev builds
- Consider forking existing chain state from mainnet?
- Not public, we control the versions; expect frequent deployments (best if we can automate this, roll out to devnet as part of ci/cd)
- Add alerts for consensus issues / metrics monitoring

**Comment by rickmak** [comment]
Let's fork existing state of testnet? Production one have over 70G.

For dev net automation, i think good to make the rollout everyweek. I doubt can it be automate.
