### ISSUE TITLE
[NFT Claim] Implement chaim stages / allowlisting

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#203]
Ref oursky/likecoin-chain#192 

- Keep schedule in ClassData: time + allowed addresses (or public)
- Check permission at claim
- Plan test cases to follow up

**Comment by hochiw** [comment]
@chihimng also belong to the config struct right?

**Comment by chihimng** [comment]
@Rico-Wong no preference on my side

btw, let's allow different price at each stage?

**Comment by hochiw** [comment]
@chihimng in this case would it be better to handle them in a nested object?
```
"config": {
	"burnable": true,
	"maxSupply": 0, // 0 = unlimited
	"payToMint": {
		"enabled": true,
		"mintPrice": 0, // 0 = free
		"mintPriceDuringClaimPeriod": 0, // 0 = free
	},
	"claimPeriod": {
		"startTime": "2022-01-01T00:00:00Z",
		"claimableAddresses": ["cosmos1"], // null = public
	}
}
```

**Comment by chihimng** [comment]
@Rico-Wong we better support multiple periods?

```json
"config": {
    ...
    "claimPeriods": [
        {
            "startTime": "",
            "allowList": [],
            "price": "",
        }
    ]
}
```

**Comment by hochiw** [comment]
👍

**Comment by mitchellchou** [comment]
claim:
means pay to mint, and create an empty NFT. 
there will be another issue for revealing NFT
