### ISSUE TITLE
[NFT Claim] Implement reveal logic

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#206]
Ref oursky/likecoin-chain#192 

- [x] Mint unclaimed tokens supply to class owner
- [x] Create metadata to token id map: shuffle by math/rand with last block app hash as seed
- [x] Call UpdateNFT to reveal all tokens
- [x] Review error modes and consider if we need to expose manual retry
- [ ] Plan test cases for follow up; note the abci test from oursky/likecoin-chain#219 is incomplete

**Comment by chihimng** [comment]
Blocked, need to merge previous issues

**Comment by chihimng** [comment]
reviewed error modes, don't think there is a workable way for class owner to fix & retry... e.g. failed to unmarshal data, failed to update nft / class at x/nft keeper, etc

if this happens, the class owner probably need to refund off-chain, or offer another collection with allowlisting for previous purchasers

(& class owner should probably test their inputs on testnet before rolling out on production)

**Comment by mitchellchou** [comment]
@chihimng Please include this to the document for the user or Dapp developers

**Comment by rickmak** [comment]
What kind of error we are talking here? Are we talking about user input error here.

**Comment by chihimng** [comment]
> What kind of error we are talking here? Are we talking about user input error here.

mostly internal errors: failed to read / update stuff at x/nft, failed to unmarshal our own data types, data inconsistency, etc
