### ISSUE TITLE
NFT Marketplace

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likecoin-chain#225]
## Spec
- Create, Update, Delete Buyer Offer
- Sell NFT with Buyer Offer
- Create, Update, Delete Seller Offer
- Purchase NFT with Seller Offer
- Queries for Offers for a NFT, option to filter out invalid offers
- Clean up expired offers according to expiry date: max expiry range at module param
- Invalid order handling: no longer owner / not enough balance - throw and delete offer, frontend should query to validate offer before proceed to avoid wasting gas fee
- Creator royalty: add royalty rate at class data & split price to class owner on transaction, max rate at module param

**Comment by chihimng** [comment]
Questions:
- Does the owner need to make a listing before buyer can make offer? or permission-less?
- Do we need to take deposits?
- Offer expiry date is a must to reduce garbage data - what should be the max length?

Draft design:
- Offer: class id, nft id, price, expire date

Tasks:
- Store & Create Buyer Offer
- Query Buyer Offer (+ Optional Filter for valid offer only?)
- Store & Create Seller Offer
- Query Seller Offer (+ Optional Filter for valid offer only?)
- Execute Buyer Offer: allow seller to take offer <= offered price
- Execute Seller Offer: allow buyer to take offer >= offered price
- Creator Royalty: Store in class config & enforce in offer execution
- Keep queue of expiry, Prune expired offers at end blocker

**Comment by rickmak** [comment]
> Does the owner need to make a listing before buyer can make offer? or permission-less?

Permission-less, no need listing.

> Do we need to take deposits?

Yes, lock the fund that the buyer offered to the owner.

> Offer expiry date is a must to reduce garbage data - what should be the max length?

Opensae is 6 mo, I think we can take this as max length.

**Comment by chihimng** [comment]
terminology update: will follow opensea to use `listing` (seller) and `offer` (buyer)

**Comment by chihimng** [comment]
also, we might want to store historical transaction (prices) for each item

**Comment by chihimng** [comment]
for creator royalty, we might want to set a upper limit (opensea is up to 10%)

**Comment by chihimng** [comment]
> The raw tx will store non-queryable history, someone will able to index them? 

actually yes, the tx events might be sufficient; dapps can index on their own; on second thought storing all history in state is too expensive on storage

**Comment by rickmak** [comment]
Yes, let's leave to to side car program.
