### ISSUE TITLE
CORS error from likecoin-skynet-1 with RPC

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likecoin-chain#234]
## Background
got CORS error from likecoin-skynet-1 with RPC, not able to test it.
`http://52.187.27.20:26657`

## Todo
- [x] Please check and see how can we fix or reply
- [x] Please assign the points of effort to this issue

ref: 
https://3.basecamp.com/3096882/buckets/25656427/messages/4826989294#__recording_4910844116

**Comment by hochiw** [comment]
Updated and replied.

**Comment by 0xtaipoian** [comment]
still not able to connect with Keplr, here my Keplr config:
```javascript
const testnet = {
    chainId: 'likecoin-skynet-1',
    chainName: 'LikeCoin public test chain',
    rpc: 'http://52.187.27.20:26657/',
    rest: 'http://52.187.27.20:26657/',
    stakeCurrency: {
      coinDenom: 'EKIL',
      coinMinimalDenom: 'nanoekil',
      coinDecimals: 9,
      coinGeckoId: 'likecoin',
    },
    walletUrlForStaking: 'https://stake.like.co',
    bip44: {
      coinType: 118,
    },
    bech32Config: {
      bech32PrefixAccAddr: 'like',
      bech32PrefixAccPub: 'likepub',
      bech32PrefixValAddr: 'likevaloper',
      bech32PrefixValPub: 'likevaloperpub',
      bech32PrefixConsAddr: 'likevalcons',
      bech32PrefixConsPub: 'likevalconspub',
    },
    currencies: [
      {
        coinDenom: 'EKIL',
        coinMinimalDenom: 'nanoekil',
        coinDecimals: 9,
        coinGeckoId: 'likecoin',
      },
    ],
    feeCurrencies: [
      {
        coinDenom: 'EKIL',
        coinMinimalDenom: 'nanoekil',
        coinDecimals: 9,
        coinGeckoId: 'likecoin',
      },
    ],
    coinType: 118,
    gasPriceStep: {
      low: 0.01,
      average: 1,
      high: 1000,
    },
    features: ['stargate', 'ibc-transfer', 'no-legacy-stdTx', 'ibc-go'],
  };
```

**Comment by hochiw** [comment]
> still not able to connect with Keplr, here my Keplr config:
> 
> ```js
> const testnet = {
>     chainId: 'likecoin-skynet-1',
>     chainName: 'LikeCoin public test chain',
>     rpc: 'http://52.187.27.20:26657/',
>     rest: 'http://52.187.27.20:26657/',
>     stakeCurrency: {
>       coinDenom: 'EKIL',
>       coinMinimalDenom: 'nanoekil',
>       coinDecimals: 9,
>       coinGeckoId: 'likecoin',
>     },
>     walletUrlForStaking: 'https://stake.like.co',
>     bip44: {
>       coinType: 118,
>     },
>     bech32Config: {
>       bech32PrefixAccAddr: 'like',
>       bech32PrefixAccPub: 'likepub',
>       bech32PrefixValAddr: 'likevaloper',
>       bech32PrefixValPub: 'likevaloperpub',
>       bech32PrefixConsAddr: 'likevalcons',
>       bech32PrefixConsPub: 'likevalconspub',
>     },
>     currencies: [
>       {
>         coinDenom: 'EKIL',
>         coinMinimalDenom: 'nanoekil',
>         coinDecimals: 9,
>         coinGeckoId: 'likecoin',
>       },
>     ],
>     feeCurrencies: [
>       {
>         coinDenom: 'EKIL',
>         coinMinimalDenom: 'nanoekil',
>         coinDecimals: 9,
>         coinGeckoId: 'likecoin',
>       },
>     ],
>     coinType: 118,
>     gasPriceStep: {
>       low: 0.01,
>       average: 1,
>       high: 1000,
>     },
>     features: ['stargate', 'ibc-transfer', 'no-legacy-stdTx', 'ibc-go'],
>   };
> ```

 @0xtaipoian skynet is using the denom `nanolike` instead of `nanoekil` but i think the `rest` field using `26657` is the main reason why it's not connecting. Could you try the config below?

```
{
  "chainId": "likecoin-skynet-1",
  "chainName": "LikeCoin SkyNet",
  "rpc": "http://52.187.27.20:26657",
  "rest": "http://52.187.27.20:1317",
  "stakeCurrency": {
    "coinDenom": "LIKE",
    "coinMinimalDenom": "nanolike",
    "coinDecimals": 9,
    "coinGeckoId": "likecoin"
  },
  "bip44": {
    "coinType": 118
  },
  "bech32Config": {
    "bech32PrefixAccAddr": "like",
    "bech32PrefixAccPub": "likepub",
    "bech32PrefixValAddr": "likevaloper",
    "bech32PrefixValPub": "likevaloperpub",
    "bech32PrefixConsAddr": "likevalcons",
    "bech32PrefixConsPub": "likevalconspub"
  },
  "currencies": [
    {
      "coinDenom": "LIKE",
      "coinMinimalDenom": "nanolike",
      "coinDecimals": 9,
      "coinGeckoId": "likecoin"
    }
  ],
  "feeCurrencies": [
    {
      "coinDenom": "LIKE",
      "coinMinimalDenom": "nanolike",
      "coinDecimals": 9,
      "coinGeckoId": "likecoin"
    }
  ],
  "coinType": 118,
  "gasPriceStep": {
    "low": 1,
    "average": 10,
    "high": 1000
  },
  "features": ["stargate", "ibc-transfer"]
}
```
