### ISSUE TITLE
[Question] liked q account address error cases

### ISSUE THREAD

**Issue by joyzoursky** [oursky/likecoin-chain#274]
## Question 1

When I create a new account on skynet through Keplr wallet, then without giving it any LIKE through faucet, and directly use `liked q account` to query the account, e.g.

```
./liked --node tcp://52.187.27.20:26657 --chain-id likecoin-skynet-1 q account like1mun3plq6cesfgvz2xfwzx2n2kkqm8k39nswvmt
```

It will show the following error:

```
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account like1mun3plq6cesfgvz2xfwzx2n2kkqm8k39nswvmt not found: key not found
```

Then after I give 1 LIKE to the account by faucet, it can show result:

```
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "28"
address: like1mun3plq6cesfgvz2xfwzx2n2kkqm8k39nswvmt
pub_key: null
sequence: "0"
```

Is this expected?

## Question 2

When an invalid address is used for the `liked q account` command (and maybe also other commands), there are different types of errors throwing according to different strings, is this expected too?

- `like1eukp0cv2hfjllxpxv7jw3p5vlrzs9a5yjyh741`
  - Error: decoding bech32 failed: invalid separator index 42 (sometimes)
- `like1eukp0cv2hfjllxpxv7jw3p5vlrzs9a5yjyh742`
  - Error: decoding bech32 failed: invalid checksum (expected jyh740 got jyh742) (most of the cases)

Except the above 2 are not sure they are differentiated, the others are clear:
- `like1twwpjural2k84rphlfv0rx957ehmyfzwgcgysgqqp` (too long or too short)
  - Error: decoding bech32 failed: invalid incomplete group
- `LIKEQFFUQJCWE4ZDMP2JX3A3SWJFTYLNPM5KHN009M` (not starting with like1)
  - Error: decoding bech32 failed: invalid separator index -1
- `1QFFUQJCWE4ZDMP2JX3A3SWJFTYLNPM5KHN009M` (not starting with like1)
  - Error: decoding bech32 failed: invalid separator index 0
- `like1qffuqjcwe4zdmp2jx3a3swjftylnpm5khn009M` (mixed cases)
  - Error: decoding bech32 failed: string not all lowercase or all uppercase

## Question 3

What is the difference between `q account [address]` and `q auth account [address]`? Seems the input and output are the same.

**Comment by mitchellchou** [comment]
Hi @joyzoursky,
Thanks for trying them out

#### Question 1
It's expected.
Because creating an account is only an off-chain (offline/local) action, you haven't had any records on the chain in any blocks. The chain knows there has this account exists after the transaction (or other on-chain interaction).


#### Question 2
It's expected when the address was invalid. The decoding was built by [cosmos-sdk](https://github.com/cosmos/cosmos-sdk)
We may more likely need to be aware if it returns errors when the address is valid.

Thanks a lot!

**Comment by joyzoursky** [comment]
@mitchellchou Thanks, got it.

Added a Q3 about `q account` vs `q auth account`, please help take a look too 🙇

**Comment by mitchellchou** [comment]
Hi @joyzoursky,

In cosmos sdk, we usually use x/auth module to query info of accounts.
`q account [address]` is probably just a shortcut to it.

Let's still run both 2 commands as our goal is to make sure nothing unexpected happens, thanks
