### ISSUE TITLE
Setup faucet for Devnet

### ISSUE THREAD

**Issue by thomas-tai-oursky** [oursky/likecoin-chain#29]

**Comment by hochiw** [comment]
@thomas-tai-oursky 

1. Install Keplr Wallet on Chrome
2. Go to [this site](https://ipfs.io/ipfs/Qme95TC2um4cxqrS1CLxBRWA5R5snftUHEwyWNMBFrVTkb)
3. Click `Add to Keplr`
4. You should see Keplr is switched to `LikeCoin Skynet`
5. Copy your wallet address
6. Go to [discord server](https://discord.gg/c975mzVYQ8)
7. In chat, send `/faucet <your_address>`
8. You should be able to see the bot processes your request
9. Go back to Keplr, switch to another network and back
10. You should see there is `1LIKE` in your account

**Comment by thomas-tai-oursky** [comment]
@Rico-Wong pls leave instruction for testnet faucet.
