### ISSUE TITLE
NFT Issuance

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#3]
References:
- [ADR-043](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-043-nft-module.md)

## User Story Draft
- Creator can create multiple classes related to an iscn
- Creator can create multiple nft under an class
- Creator can update class metadata
- Creator can toggle burnable flag of a class
- Users can list all classes related to an iscn
- Users can look up / validate that an nft / class is related to an iscn
- Token owner can burn token if class's burnable flag is true

## Technical Requirements
- We consider `IscnIdPrefix` (`<registry-code>/<unique-id>` or `1/abc-xyz-123`) as canonical id of the iscn record here, i.e. iscn referred here represents the set of all versions of the iscn record, not a particular version.
- Conform to `x/nft` and `proto/cosmos/nft` interface: try to backport cosmos-sdk master branch one; at release time we should import the module as library, avoid copy code
- Object relation: `ISCN 1 - n Class 1 - n NFT`
- Method to create nft `class` under an iscn, add iscn relation metadata at `uri` or `data` field
-> Need to store the "canonical" relations at `x/iscn`
- Method to look up `class` related to one iscn, & in reverse'

## Planning
- Setup dev environment (try to adopt starport) oursky/likecoin-chain#9
- Integrate x/nft (+ risk: might have to handle sdk version upgrade) oursky/likecoin-chain#10
- Add storage and method to create nft class (`NewClass`) oursky/likecoin-chain#11
- Add query method to list classes under an iscn oursky/likecoin-chain#12
- Add query method in x/iscn to lookup iscn with nft class id oursky/likecoin-chain#13
- Add method to update class (`UpdateClass`) oursky/likecoin-chain#32
- Add method to create nft (`MintNFT`) oursky/likecoin-chain#33
- Add method to burn nft (`BurnNFT`) and toggle burnable flag in class oursky/likecoin-chain#34
- (Will not implement `UpdateNFT` method)
- Command line interface oursky/likecoin-chain#14
- RPC interface oursky/likecoin-chain#15
- Test cases oursky/likecoin-chain#16

**Comment by thomas-tai-oursky** [comment]
@chihimng  Study these 2 PR as provided by @rickmak:
https://github.com/WeiJun0827/likecoin-chain/pull/2#issuecomment-1024050339
https://github.com/WeiJun0827/likecoin-chain/pull/1#issuecomment-1024046042

**Comment by chihimng** [comment]
Summarizing offline discussion:

- At release time, we will aim to adopt `x/nft` as a library import (instead of cloning module code to our repo). The module is expected to be included in cosmos sdk v0.46 (v8-Rho Upgrade, Q2 2022) 
- In the meantime, we shall try to backport `x/nft` and `proto/cosmos/nft` to our repo first, and begin development of relating iscn to a class / collection. The consensus today is that the object relation will be: `ISCN 1 - 1 Class 1 - N NFT`

@rickmak will coordinate with other teams on sdk version upgrades & release timelines - currently we are on v0.42. Probably we should first upgrade to v0.44 at Q1 (along with prefix migration?) and then v0.46 along with nft support at Q2

**Comment by chihimng** [comment]
Added follow up story #8 for tracking claiming feature
