### ISSUE TITLE
Upgrade to cosmos-sdk 0.45

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likecoin-chain#302]
## Background
During the meeting with William and Kin and Phoebe, confirmed we don't wait for 0.46 release.

## Todo
- [x] Please check if we have any implementation that only compatible with 0.46 (or based on 0.46 spec)
- [ ] Upgrade to cosmos-sdk 0.45

**Comment by chihimng** [comment]
we should update the backported x/nft to 0.46-rc0 as well

**Comment by chihimng** [comment]
- need to ask chung / william to help rebase the sdk fork to 0.45.x
- we will review migration docs and implement the upgrade handler

**Comment by chihimng** [comment]
> Chain Upgrade Guide to v0.45: no migration is required. See Release Notes and changelog for the list of API and State Machine breaking changes.

https://github.com/cosmos/cosmos-sdk/tree/v0.45.5/docs/migrations

will need to check ibc next

**Comment by rickmak** [comment]
Tracking issue for sdk fork rebase: https://github.com/likecoin/likecoin-chain/issues/77

**Comment by mitchellchou** [comment]
@hochiw Please check

**Comment by chihimng** [comment]
checked ibc-go, latest minor is v2.3.0 & requires a migration: https://github.com/cosmos/ibc-go/releases/tag/v2.3.0 (we are on 2.1.0 now)

i guess we will not upgrade to v3.x, which supports interchain account, but requires extra time for us to look into the complications

cc @rickmak
