### ISSUE TITLE
[SDK 0.45] Increment go module version name to v3

### ISSUE THREAD

**Issue by williamchong** [oursky/likecoin-chain#305]
Can we increment the go package version to `github.com/likecoin/likecoin-chain/v3` ?
e.g. our v2 PR https://github.com/likecoin/likecoin-chain/pull/73
This allow us to use 3.0.0 in other go app like indexer

**Comment by rickmak** [comment]
I think we should do it when we rebase everything onto 0.45? @chihimng

**Comment by chihimng** [comment]
Ref story #302
