### ISSUE TITLE
Build and push rbuilder with go 1.18.3

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#320]
Updated source at https://github.com/oursky/tendermint-images/tree/rbuilder-go1.18.3

After checkout, on m1 mac:
```sh
cd rbuilder
docker buildx build --platform=linux/amd64 -o type=docker . -t likecoin/rbuilder:go1.18.3
docker push likecoin/rbuilder:go1.18.3
```
(or build normally on x86 machine)

Afterwards, we need to update usages in chain repo's makefile and root docker image

**Comment by chihimng** [comment]
@rickmak can you help with this as i don't have access to likecoin's docker repo?

**Comment by rickmak** [comment]
Built and pushed.

https://hub.docker.com/layers/rbuilder/likecoin/rbuilder/go1.18.3/images/sha256-045feb8628aa3e91fa876b3794db60be9143013df5f14826cab86d69f0487436?context=explore

**Comment by chihimng** [comment]
thanks; we might want to tag latest too btw, just in case...

![image.png](https://zube.io/files/oursky/2bd6e53eb9d8f73d31e99ecb5660a684-image.png)

**Comment by rickmak** [comment]
Thanks for remind, pushed the latest tag too.
