### ISSUE TITLE
NFT Part 2

### ISSUE THREAD

**Issue by chihimng** [oursky/likecoin-chain#8]
(Spec Adjustment)
- Allow relating nft class to account, in addition to iscn; Update CRUD methods / queries

(Creator Monetization)
- Set mint-price and max-supply at class
- Claim / Pay to mint feature

(Marketplace - Pending)
- Create, Update, Delete Buyer Offer
- Sell NFT with Buyer Offer
- Create, Update, Delete Seller Offer
- Purchase NFT with Seller Offer
- Queries for Offers for a NFT, option to filter out invalid offers
- Clean up expired offers according to expiry date: max expiry range at module param
- Invalid order handling: no longer owner / not enough balance - throw and delete offer, frontend should query to validate offer before proceed to avoid wasting gas fee
- Creator royalty: add royalty rate at class data & split price to class owner on transaction, max rate at module param

(Test cases - Pending)

**Comment by chihimng** [comment]
updated details for iscn owner cut

**Comment by chihimng** [comment]
Related: iscn stakeholder metadata https://github.com/likecoin/iscn-specs/blob/master/schema/stakeholders/README.md

should consider this when splitting royalty

**Comment by mitchellchou** [comment]
@Rico-Wong Please open tasks for test cases

**Comment by mitchellchou** [comment]
@chihimng Please help to revise the spec

**Comment by chihimng** [comment]
@mitchellchou updated 🙏
